name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Clone, build, and run tests inside the Nix environment
    - name: Run lean-mlir experiments
      run: |
        # enter into submodule.
        cd lean-mlir && git show HEAD && nix run .#test-experiments
