name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Clone, build, and run tests inside the Nix environment
    - name: Run lean-mlir experiments
      run: |
        # enter into submodule.
        cd lean-mlir

        # 2. Build the project artifacts using nix-build
        nix-build

        # 3. Run the script INSIDE the nix environment
        # nix-shell provides the necessary runtime dependencies
        nix-shell --run 'lake build SSA'
        nix-shell --run './artifacts/oopsla25-width-indep/run_experiments.sh'
