name: "Run Evaluation CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Clone, build, and run tests inside the Nix environment
    - name: Run lean-mlir experiments
      run: |
        git submodule update --init
        git show HEAD
        git clone git@github.com:opencompl/lean-mlir.git
        git checkout 85ad52b
        cd lean-mlir
        git show HEAD
        cd lean-mlir && git show HEAD && nix run .#test-experiments
